version: "3.1"

services:
  solr:
    image: solr:7-slim
    restart: "${CKAN_RESTART_POLICY:-no}"
    ulimits:
      nofile:
        soft: 65000
        hard: 65000
    hostname: solr
    volumes:
      - "./solr/conf:/opt/solr/server/solr/ckan"
      - "${SOLR_DATA_HOST_FOLDER:-./solr_data}:/opt/solr/server/solr/ckan/data"

  postgres:
    image: postgres:11-alpine
    restart: "${CKAN_RESTART_POLICY:-no}"
    hostname: postgres
    env_file:
      - ./postgres/postgres.env
    volumes:
      - "${POSTGRES_DATA_HOST_FOLDER:-./postgres_data}:/var/lib/postgresql/data"

  dataproxy:
    image: unocha/hdx-dataproxy:2.5
    restart: "${CKAN_RESTART_POLICY:-no}"
    hostname: dataproxy
    ports:
      - "127.0.0.1:5001:5000"

  ckan:
    image: mgalex/ckan_with_docker:0.0.1-a1
#    build: ../.
    restart: "${CKAN_RESTART_POLICY:-no}"
    hostname: ckan
    depends_on:
      - solr
      - postgres
    volumes:
      - "./ckan/etc:/etc/ckan"
      - "${CKAN_DATA_HOST_FOLDER:-./ckan_data}:/var/lib/ckan"
    ports:
      - "127.0.0.1:5000:5000"
#    entrypoint: "tail -f /dev/null"
    entrypoint: /bin/bash -c "ln -sf /etc/ckan/ckan.ini ckan.ini && gunicorn -w 2 -b 0.0.0.0:5000 wsgi:application"

